### ISSUE TITLE
Recompile needed

### ISSUE THREAD

**Issue by M-archand** [Source2ZE/CleanerCS2#1]
I hate to make such a trivial ask, as I have been meaning to learn how to compile metamod based plugins... but would you mind updating the release to be compatible with the latest version of metamod?  I find this plugin very useful and miss having a clean server console <3

**Comment by Vauff** [comment]
v1.0.3 was already recompiled.

**Comment by M-archand** [comment]
@Vauff Thank you, I didn't realize you could update releases like that without making a new one 👍
